/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class concurrency_start_MyThread */

#ifndef _Included_concurrency_start_MyThread
#define _Included_concurrency_start_MyThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     concurrency_start_MyThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_concurrency_start_MyThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
